// Copyright 2024 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.

#include "xsk/gsc/engine/s4.hpp"

namespace xsk::gsc::s4
{

extern std::array<std::pair<u32, char const*>, token_count> const token_list
{{
    { 0x0048, "alpha" } ,
    { 0x0055, "angles" },
    { 0x0073, "attacker" } ,
    { 0x0089, "basename" },
    { 0x00E8, "classname" },
    { 0x0145, "damage" },
    { 0x0149, "damagemod" },
    { 0x014F, "damageweapon" },
    { 0x022D, "ignoreme" },
    { 0x0265, "killcamentity" },
    { 0x029D, "maxhealth" },
    { 0x02CE, "model" } ,
    { 0x02CF, "modelname" } ,
    { 0x030A, "origin" },
    { 0x0312, "owner" } ,
    { 0x0329, "pers" } ,
    { 0x032F, "player" },
    { 0x034D, "primaryweapons" } ,
    { 0x03B8, "sessionstate" } ,
    { 0x03EE, "speed" },
    { 0x03EF, "speedscalemult" } ,
    { 0x047E, "target" },
    { 0x0482, "team" } ,
    { 0x04A1, "trigger" },
    { 0x04B6, "type" } ,
    { 0x04FD, "weaponinfo" },
    { 0x06D9, "scripts/common/input_allow" },
    { 0x06E4, "scripts/common/utility" },
    { 0x06E6, "scripts/common/vehicle" },
    { 0x0794, "scripts/cp_mp/hostmigration" },
    { 0x07A0, "scripts/engine/math" },
    { 0x07A3, "scripts/engine/trace" } ,
    { 0x07A4, "scripts/engine/utility" },
    { 0x07E0, "scripts/mp/hostmigration" },
    { 0x07E3, "scripts/mp/hud_util" },
    { 0x07F6, "scripts/mp/movers" } ,
    { 0x07FE, "scripts/mp/persistence" },
    { 0x081B, "scripts/mp/supers" },
    { 0x0959, "scripts/mp/utility/entity" } ,
    { 0x09C2, "scripts/cp_mp/utility/game_utility" } ,
    { 0x09C3, "scripts/cp_mp/utility/inventory_utility" },
    { 0x09C4, "scripts/cp_mp/utility/killstreak_utility" },
    { 0x09C5, "scripts/cp_mp/utility/player_utility" },
    { 0x09C6, "scripts/cp_mp/utility/script_utility" },
    { 0x09DD, "scripts/cp_mp/vehicles/vehicle" },
    { 0x09DF, "scripts/cp_mp/vehicles/vehicle_damage" } ,
    { 0x09E3, "scripts/cp_mp/vehicles/vehicle_occupancy" },
    { 0x09E4, "scripts/cp_mp/vehicles/vehicle_spawn" },
    { 0x09E5, "scripts/cp_mp/vehicles/vehicle_tracking" } ,
    { 0x0A48, "scripts/mp/killstreaks/helicopter" },
    { 0x0A51, "scripts/mp/killstreaks/killstreaks" },
    { 0x0A73, "scripts/mp/tac_ops/hostage_utility" } ,
    { 0x0A90, "scripts/mp/utility/entity" },
    { 0x0A92, "scripts/mp/utility/game" } ,
    { 0x0A98, "scripts/mp/utility/killstreak" },
    { 0x0A9B, "scripts/mp/utility/outline" },
    { 0x0A9C, "scripts/mp/utility/perk" },
    { 0x0A9D, "scripts/mp/utility/player" } ,
    { 0x0AA5, "scripts/mp/utility/teams" },
    { 0x0B75, "_bullet_trace" } ,
    { 0x0BCC, "_effect" } ,
    { 0x0BED, "_freezecontrols" },
    { 0x0C14, "_giveweapon" },
    { 0x0C1F, "_hasperk" },
    { 0x0C3D, "_isalive" },
    { 0x0D81, "_spawnvehicle" } ,
    { 0x0D93, "_takeweapon" },
    { 0x154A, "allow_input_internal" },
    { 0x1715, "ammocount" },
    { 0x1B8B, "array_add" },
    { 0x1BA0, "array_contains" },
    { 0x1BBC, "array_randomize" },
    { 0x1BC4, "array_remove_index" },
    { 0x2AA9, "br_quests_enabled" },
    { 0x2AAA, "br_queststashlocations" },
    { 0x2DDD, "buttonspressed" },
    { 0x32F6, "carryweapon" },
    { 0x33FD, "characters" },
    { 0x364B, "chopper_fx" } ,
    { 0x3FF8, "createicon" } ,
    { 0x41B0, "currentactivevehiclecount" },
    { 0x46E4, "delaythread" } ,
    { 0x484D, "destroyelem" } ,
    { 0x4D41, "domonitoredweaponswitch" } ,
    { 0x5242, "enabledcollisionnotifies" },
    { 0x5247, "enabledignoreme" },
    { 0x60BA, "gameended" },
    { 0x60F0, "gametype" } ,
    { 0x69AC, "getcurrentsuper" },
    { 0x6A0A, "getentitiesinradius" } ,
    { 0x6A5F, "getfx" },
    { 0x6A62, "getgametype" },
    { 0x6D24, "getsharedfunc" } ,
    { 0x6D98, "getstruct" },
    { 0x6D9A, "getstructarray" },
    { 0x6FF7, "givesuper" },
    { 0x71D4, "groundpos" },
    { 0x725C, "guid" },
    { 0x7260, "guidgen" } ,
    { 0x75BB, "hastag" },
    { 0x7AA6, "hostmigration_waitlongdurationwithpause" },
    { 0x7E93, "inflictor" },
    { 0x82C6, "inlaststand" } ,
    { 0x8669, "is_player_gamepad_enabled" },
    { 0x87D4, "iscp" },
    { 0x881D, "isenemy" },
    { 0x893A, "ismp" },
    { 0x8940, "isnightmap" },
    { 0x89ED, "isreallyalive" },
    { 0x8A0B, "isroundbased" } ,
    { 0x8A2A, "issharedfuncdefined" },
    { 0x8A46, "issp" } ,
    { 0x8D62, "killcament" } ,
    { 0x9ABE, "mapname" } ,
    { 0x9BCA, "matchmakinggame" },
    { 0x9CAE, "maxteamsize" },
    { 0x9CB9, "maxvehiclesallowed" },
    { 0x9FD0, "modelbase" } ,
    { 0xA91E, "objweapon" },
    { 0xACCA, "outlinedisable" },
    { 0xACD0, "outlineenableforplayer" },
    { 0xB76B, "players" },
    { 0xBBEF, "pressed" },
    { 0xBCE0, "primaryweaponclipammo" } ,
    { 0xBCE1, "primaryweaponobj" } ,
    { 0xBCE2, "primaryweaponstockammo" } ,
    { 0xC050, "ray_trace" },
    { 0xC055, "ray_trace_passed" } ,
    { 0xCFEB, "secondaryweaponobj" } ,
    { 0xD295, "set_movement_speed" },
    { 0xD681, "setpoint" } ,
    { 0xD722, "setthirdpersondof" },
    { 0xE20F, "spawn_tag_origin" } ,
    { 0xEA0E, "streakinfo" } ,
    { 0xEA12, "streakname" },
    { 0xEA58, "string_starts_with" },
    { 0xEF65, "teambased" },
    { 0xF082, "ter_op" },
    { 0xFE9D, "useotherobj" },
    { 0xFEA0, "useownerobj" },
    { 0xFEF2, "useweapon" } ,
    { 0xFFF3, "vehicle" },
    { 0x10026, "vehicle_create" },
    { 0x10265, "vehicle_spawn" },
    { 0x10276, "vehicle_spawn_getleveldataforvehicle" } ,
    { 0x10312, "vehicleinfo" },
    { 0x1084F, "waitlongdurationwithhostmigrationpause" },
    { 0x10880, "waittill_any_2" },
    { 0x10881, "waittill_any_3" },
    { 0x10DA9, "weaponlist" },
    { 0x10DC9, "weapons" },
}};

} // namespace xsk::gsc::s4
